FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_UPLOAD_API_URL
ARG NEXT_PUBLIC_REST_API_URL

ENV NEXT_PUBLIC_UPLOAD_API_URL=$NEXT_PUBLIC_UPLOAD_API_URL
ENV NEXT_PUBLIC_REST_API_URL=$NEXT_PUBLIC_REST_API_URL

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
